replicaCount: 1

image:
  repository: XXX.ocir.io/XXX/XXX/mushop-fulfillment
  tag: 1.1.0
  pullPolicy: IfNotPresent

osb: {}

env:
  natsHost: "nats"
  natsPort: 4222
  newOrdersSubject: mushop-orders
  shippedOrdersSubject: mushop-shipments
  simulationDelay: 10000

service:
  port: 80
