replicaCount: 1

image:
  repository: XXX.ocir.io/XXX/XXX/mushop-carts
  tag: 1.5.0
  pullPolicy: IfNotPresent

dbtools:
  repository: XXX.ocir.io/XXX/XXX/mushop-dbtools
  tag: 1.0.1
  pullPolicy: IfNotPresent

osb: {}

secrets:
  oadbService:
  oadbUser:
  oadbPassword:
  oadbWalletPassword:

env:
  zipkin: zipkin.jaeger.svc.cluster.local
  javaOpts: -Xms64m -Xmx128m -XX:+UseG1GC -Dlogging.level.mushop.carts=TRACE  -Djava.security.egd=file:/dev/urandom -Dspring.zipkin.enabled=false

service:
  port: 80
